### ISSUE TITLE
Update PyPI release

### ISSUE THREAD

**Issue by Shivelight** [yimingliu/py-natpmp#13]
There are multiple commits pushed which include fixes and improvement, and also Python 3 support. An update would be nice.

**Comment by yimingliu** [comment]
https://pypi.org/manage/project/py-natpmp/release/0.2.5/

packaged and sent the latest updates to PyPI.  Hopefully i did that correctly -- things are a bit different since 2016, when I last did this.

**Comment by Shivelight** [comment]
Works fine here. Thank you 👍
